### ISSUE TITLE
adonis-autoswagger

### ISSUE THREAD

**Issue by ad-on-is** [adonisjs-community/adonis-packages#21]
Hey, I created an automated swagger based on existing routes and models with the ability to extend these with simple comments above the controller actions.

https://github.com/ad-on-is/adonis-autoswagger

https://www.npmjs.com/package/adonis-autoswagger

**Comment by Julien-R44** [comment]
Hey! Can you do a PR for this please? Thanks

**Comment by RomainLanz** [comment]
Closing since no answer from issue reporter.
