### ISSUE TITLE
adonisjs-maintenance

### ISSUE THREAD

**Issue by MichaelBelgium** [adonisjs-community/adonis-packages#42]
Would y'all be open to add my package ? But I don't really have an icon for it 

https://www.npmjs.com/package/adonisjs-maintenance
https://github.com/MichaelBelgium/adonisjs-maintenance

Not sure about adonisJS v6 and if it will have a maintenance mode, but at least i gained some experience :D

**Comment by Julien-R44** [comment]
cool ! can you create a PR for that please?
