### ISSUE TITLE
Add a filter on type '1st pary' or '3rd-party' plugin

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs-community/adonis-packages#44]
Hello,

This could help users to find plugins from Adonis.

**Comment by Julien-R44** [comment]
Yeah definitely. Same, i would like to have a filter to select packages compatible with Adonis 5, Adonis 6, or both. 
But I'm not sure how to approach it from a UI/UX point of view. Mostly UI. I had tried something but it was ugly ahah

If you have a suggestion, please let me know. I will think about it too

**Comment by Barbapapazes** [comment]
I'll try something once #52 is resolved!

**Comment by Barbapapazes** [comment]
I'm working on it. Expect a PR this evening.
