### ISSUE TITLE
Standardize the colors with the documentation

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs-community/adonis-packages#5]
Wouldn't it be necessary, to make the environment more pleasant, to standardize the colors between the documentation (which now has a dark theme) and the site containing the packages (especially since the site is very dark anyway)?

**Comment by Julien-R44** [comment]
Yeah would be cool ! I had just taken the colors of the dark mode of this site for the doc of Adonis, but they were not appreciated by everyone, so we have to make the opposite change 👍

**Comment by Julien-R44** [comment]
Done ! 

Let me know what you think about it, and feel free to make a PR if you have time and see something we need to change

**Comment by Barbapapazes** [comment]
Whoo fast! I'll watch tonight!

**Comment by Barbapapazes** [comment]
Perfect, I think it makes the site more readable and it allows to have a harmony with the documentation! 

Thanks for the speed!
